eng = {
'choose_file_btn': 'Choose File',
'choose_dir_btn': 'Change',
'gen_btn': 'Generate',
'snap_chk': 'Snap Waypoints Time',
'wait_stat': 'Waiting For a File',
'ready_stat': 'Press "Generate" to Start',
'doing_stat': 'In Progress',
'done_stat': 'Done',
'no_trks': 'No Tracks Found',
'no_pnts': 'No Points Found',
'format_wrn': 'Selected File is in Wrong Format',
'no_file_wrn': 'File Doesn'+"'"+'t Exist',
'trk_count_1': 'Track Processed',
'trk_count_2': 'Tracks Processed',
'trk_count_3': 'Tracks Processed',
'length': 'km Total',
'pnt_count_1': 'Point',
'pnt_count_2': 'Points',
'pnt_count_3': 'Points',
'snapped_1': 'Snapped',
'snapped_2': 'Snapped',
'lang': 'Language',
'f_dial': 'Choose a GPX file',
'd_dial': 'Choose folder containing elevation files',
'set_btn': 'Settings',
'help_btn': 'Help',
'dir_set': 'HGT Folder',
'save': 'Save',
'trk_proc': 'Processing a Track',
'pnt_proc': 'Processing a Point',
'too_long': 'Processing takes too much time, track might be too long',
'wrong': 'Something went wrong during processing closing the programm is recommended',
'save': 'Save',
'wait': 'Please, Wait',
'reading': 'Reading the GPX File',
'creator': 'Creator Name',
'inter': 'Interpolate',
'timeshift': 'Timezone(relative to UTC)'
}

rus = {
'choose_file_btn': 'Выберите Файл',
'choose_dir_btn': 'Изменить',
'gen_btn': 'Сгенерировать',
'snap_chk': 'Привязывать Время Точек',
'wait_stat': 'В Ожидании Файла',
'ready_stat': 'Нажмите "Сгенерировать" Чтобы Начать',
'doing_stat': 'В Процессе',
'done_stat': 'Готово',
'no_trks': 'Треки Не Найдены',
'no_pnts': 'Точки Не Найдены',
'format_wrn': 'Выбранный Файл Имеет Несовместимый Формат',
'no_file_wrn': 'Файл Не Существует',
'trk_count_1': 'Трек Обработан',
'trk_count_2': 'Трека Обработано',
'trk_count_3': 'Треков Обработано',
'length': 'км в Общем',
'pnt_count_1': 'Точка',
'pnt_count_2': 'Точки',
'pnt_count_3': 'Точек',
'snapped_1': 'Привязана',
'snapped_2': 'Привязано',
'lang': 'Язык',
'f_dial': 'Выберите GPX Файл',
'd_dial': 'Выберите Папку с Файлами Высот',
'set_btn': 'Настройки',
'help_btn': 'Помощь',
'dir_set': 'Папка HGT',
'save': 'Сохранить',
'trk_proc': 'Обрабатывается Трек',
'pnt_proc': 'Обрабатывается Точка',
'too_long': 'Обработка занимает много времени, вероятно трек слишком длинный',
'wrong': 'Что-то пошло не так при обработке, рекомендуется закрыть программу',
'wait': 'Пожалуйста, Подождите',
'reading': 'Считывается GPX Файл',
'creator': 'Имя Создателя',
'inter': 'Интреполировать',
'timeshift': 'Часовой пояс(относительно UTC)'
}

langs = {
'eng': eng,
'rus': rus
}

#langs.get('lang_name', ln.eng).get('element', '***') how to get a value

months = {  #dictionary for months formats
    "Jan": 1,
    "Feb": 2,
    "Mar": 3,
    "Apr": 4,
    "May": 5,
    "Jun": 6,
    "Jul": 7,
    "Aug": 8,
    "Sep": 9,
    "Oct": 10,
    "Nov": 11,
    "Dec": 12,
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12,
    "Jan.": 1,
    "Feb.": 2,
    "Mar.": 3,
    "Apr.": 4,
    "May.": 5,
    "Jun.": 6,
    "Jul.": 7,
    "Aug.": 8,
    "Sep.": 9,
    "Oct.": 10,
    "Nov.": 11,
    "Dec.": 12
}

daycounts_normal = {
    1: 31,
    2: 28,
    3: 31,
    4: 30,
    5: 31,
    6: 30,
    7: 31,
    8: 31,
    9: 30,
    10: 31,
    11: 30,
    12: 31,
}

daycounts_leap = {
    1: 31,
    2: 29,
    3: 31,
    4: 30,
    5: 31,
    6: 30,
    7: 31,
    8: 31,
    9: 30,
    10: 31,
    11: 30,
    12: 31,
}